### ISSUE TITLE
ability to reverse an extract operation with ctrl+z

### ISSUE THREAD

**Issue by DavidGretzschel** [supermemo/SuperMemoAssistant#111]
feature request:

scenario:
Trouble is, if you do an extract in SuperMemo and you regret it, you have weird blue text in your source item, even if you delete the extracted topic. You can't easily remove this formatting either, which is disheartening.

In SMA>PDF it's blue or red text as well as weird red overlays. It would be great, if ctrl+z could reverse this formatting and delete the extracted topic as if nothing ever happened.

![image](https://user-images.githubusercontent.com/23729465/75164869-bb87d500-5721-11ea-8c1c-95edc7565c4d.png)

**Comment by nikedinikedi** [comment]
Issue moved to [supermemo/SuperMemoAssistant.Plugins.PDF #74](https://github.com/supermemo/SuperMemoAssistant.Plugins.PDF/issues/74) via [**ZenHub**](https://www.zenhub.com/)
