### ISSUE TITLE
disable left-click for area selection in SMA>PDF

### ISSUE THREAD

**Issue by DavidGretzschel** [supermemo/SuperMemoAssistant#114]
Area-Selection should only be doable with a right click drag operation. And the left click drag should only be used for text selection.

This would enormously simplify the documentation in the wiki, as all references to a "force selection" can simply be replaced by "area selection".
There's no extra value to allowing a left-click drag to make an area-selection, since it's just more confusing that left-click will do different things depending on context. It also forces the user to start the selection precisely at the letter, that's targeted, which just wastes time.

**Comment by DavidGretzschel** [comment]
ctrl+f "would be right-click only. Having left" in #sma-ideas for extra discussion on this.

**Comment by nikedinikedi** [comment]
Issue moved to [supermemo/SuperMemoAssistant.Plugins.PDF #73](https://github.com/supermemo/SuperMemoAssistant.Plugins.PDF/issues/73) via [**ZenHub**](https://www.zenhub.com/)
