### ISSUE TITLE
caret selection in SMA>PDF

### ISSUE THREAD

**Issue by DavidGretzschel** [supermemo/SuperMemoAssistant#115]
A computer mouse is an analog tool useful for analog problems (like clicking on a target in a computer game), it is not well-suited for dealing with discrete information like text in a PDF.

Whilst a mouse might work adequately in most cases, a trackpad, a touch crystal or a ThinkPad-nub usually perform much worse. Mobilie productivity with SMA is thus strongly impaired.

Thus I suggest a way to insert a caret/text cursor into the PDF-viewer with which one can select text more quickly. It could work in the following way:

ctrl+k sets a controllable text cursor at the top line of the current page to the very left.
Ctrl+k or extracting a Selection should remove the cursor.

This cursor should move like a normal text cursor via arrow keys. Up/Down should make the cursor go up/down lines. Pos1/End should go to the beginning/end of a line.
PgUp/PgDwn should move the cursor a half page up/down each.
Ctrl+right/left should move the cursor a word to the right/left.

Holding down shift during any of those movements should select the text that the cursor passes during the movement.

Making these basic functionalities remappable would be very welcome, too so that someone so inclined could even add basic Vim-keybindings.

**Comment by DavidGretzschel** [comment]
Also, I just found out that typing whilst walking on a office treadmill is fairly easy.
But using the mouse is extremely difficult!
The shock of each step throws me off my target.
And standing around or even sitting all day isn't very healthy. You wouldn't want SMA to be dangerous to health, now would you :)

**Comment by nikedinikedi** [comment]
Issue moved to [supermemo/SuperMemoAssistant.Plugins.PDF #72](https://github.com/supermemo/SuperMemoAssistant.Plugins.PDF/issues/72) via [**ZenHub**](https://www.zenhub.com/)
