### ISSUE TITLE
[Collection selection] Browse should open explorer in C:\SuperMemo\Systems rather than Documents in first time startup

### ISSUE THREAD

**Issue by DavidGretzschel** [supermemo/SuperMemoAssistant#121]
Because that's where 90% of users actually store their collections. And even the remaining ten percent are unlikely to store them in "Documents".

![image](https://user-images.githubusercontent.com/23729465/75169368-b37f6380-5728-11ea-9bfe-510b66fc78e6.png)

**Comment by alexis-** [comment]
Related https://github.com/supermemo/SuperMemoAssistant/issues/73

**Comment by alexis-** [comment]
Implemented <https://github.com/supermemo/SuperMemoAssistant/issues/73>, closing this issue.
