### ISSUE TITLE
Dictionary Settings tabbing broken

### ISSUE THREAD

**Issue by DavidGretzschel** [supermemo/SuperMemoAssistant#122]
https://www.loom.com/share/7b09bb7d57e141b68517ecc5a43bee9b

**Comment by DavidGretzschel** [comment]
reverse:
https://www.loom.com/share/0da8dedba1664a7a929ea3dc9a63dba8

**Comment by DavidGretzschel** [comment]
In this case "tab" should select a setting below, whereas ctrl+tab or ctrl+shift+tab should exclusively switch tabs and do nothing else, cause that's how the world normally works.
Don't subvert user expectations with random stuff, they don't like that.

**Comment by DavidGretzschel** [comment]
Similar behaviour in the other settings-subwindows.

**Comment by nikedinikedi** [comment]
Issue moved to [supermemo/SuperMemoAssistant.Plugins.Dictionary #4](https://github.com/supermemo/SuperMemoAssistant.Plugins.Dictionary/issues/4) via [**ZenHub**](https://www.zenhub.com/)
