### ISSUE TITLE
ctrl+ and ctrl- should zoom in SMA>PDF

### ISSUE THREAD

**Issue by DavidGretzschel** [supermemo/SuperMemoAssistant#123]
Relying on the mousewheel for the zoom functionality is a bad idea. You don't always have a mouse available, after all.
And ctrl+ and ctrl- are the traditional shortcuts for this operation. If those are implemented new users adopting SMA will feel more at home.

**Comment by nikedinikedi** [comment]
Issue moved to [supermemo/SuperMemoAssistant.Plugins.PDF #71](https://github.com/supermemo/SuperMemoAssistant.Plugins.PDF/issues/71) via [**ZenHub**](https://www.zenhub.com/)
