### ISSUE TITLE
Article sharing / Link sharing / Article suggesting feature

### ISSUE THREAD

**Issue by nikedinikedi** [supermemo/SuperMemoAssistant#213]
#### Description

Simple hotkey to grab link from article you are reading in SM and placing it into dedicated collection of user shared links (by categories defined by user)

#### Sketches, Videos, explanation

**Step 1: You come across some interesting article in SM and find very much value of it......**

![image](https://user-images.githubusercontent.com/51511831/82089351-254dc480-96fc-11ea-9e2f-3e0d1985ff98.png)

**Step 2: You press hotkey to share the link of article to dedicated place in SMA (collection of links shared by users categorized)....**

![image](https://user-images.githubusercontent.com/51511831/82091672-719b0380-9700-11ea-836f-baa71cd0ea9d.png)

**Step 3: The links are placed in golden nugget palace (name in progress) where people can find valuable material from other users**

![image](https://user-images.githubusercontent.com/51511831/82089742-de140380-96fc-11ea-8132-7bc715e65201.png)

#### Motivation
Material selection is one of the most important aspects in SM. There's been talk about "awesome supermemo" and similiar things that this post is about. I find the link sharing to be convinent way of implementing a collection of valuable material. (you do it by couple clicks and link is grabbed automatically for you)

**Comment by nikedinikedi** [comment]
@bjsi and strategypattern is working on this. www.goldennuggetpalace.com

**Comment by bjsi** [comment]
Link to SMA plugin (WIP) [here](https://github.com/bjsi/SuperMemoAssistant.Plugins.NuggetPalace)
