### ISSUE TITLE
How to make the forge forms dialog popup? 

### ISSUE THREAD

**Issue by candywal** [supermemo/SuperMemoAssistant#218]
The dialog was not popping up when I used await ```Show.Dialog().For<PopUp>(popUp);```. To fix this you need to change the Dialog to Window await i.e. ```Show.Window().For<PopUp>(popUp);```.

**Comment by alexis-** [comment]
This is specific to Forge.Forms. Dialog requires you to have a host in your WPF window: https://wpf-forge.github.io/Forge.Forms/guides/getting-started.html
