### ISSUE TITLE
Issue that needs you to rerun the plugin in order to get it to work

### ISSUE THREAD

**Issue by candywal** [supermemo/SuperMemoAssistant#228]
#### Description
some plugin won't startup on run of SMA. I think this is a problem with when there is a hotkey that needs to create a pop up. Basically, the dictionary plugin and some other plugins I made which have a hot key will not run unless I press cntrl + shift + alt + O and restart them. Then they work fine. 

#### Steps to Reproduce
With the dictionary plugin after running SM through SMA pressing Cntrl Alt D on a highlighted text does not work, but if you restart the plugin by pressing pause and play it works. 

#### Expected behavior
The plugin should work without having the need to restart it. 

#### Environment (fill where applicable)
- **Version**: [e.g. SMA 2.0.5-alpha.15 and Dictionary 2.0.5-alpha.4 other plugins which have a hotkey and a popup window] 
- **Last version that did not exhibit the issue**: I am not sure
- **SM Version**: [e.g. SM 18.04]
- **OS**: [e.g. Windows 10 64bit]
- **OS Language**: [e.g. English (USA), English (India)] 
- **Browser**: [e.g. Chrome]

**Comment by alexis-** [comment]
Thanks, that's very detailed

**Comment by alexis-** [comment]
Should be fixed.

**Comment by candywal** [comment]
Awesome!
