### ISSUE TITLE
Answer Component doesn't have the "Answer" selected 

### ISSUE THREAD

**Issue by Fowl95** [supermemo/SuperMemoAssistant#234]
When using elemBuilder, like this: 
var elemBuilder = new ElementBuilder(
              ElementType.Item,
              questionContent,
              answerContent);
The Answer component does not have the "Answer" option ticked on, meaning that items show the answer field during review, unless you tick the option manually. Please add the parameter

**Comment by bjsi** [comment]
Solution: add AtFlags.NonQuestion as the displayAt parameter when you create your TextContent.
![image](https://user-images.githubusercontent.com/58147075/89100745-7a42d200-d3f1-11ea-8133-e7feb99a5009.png)

**Comment by alexis-** [comment]
@bjsi saved the day
