### ISSUE TITLE
A mouse movement / scroll event

### ISSUE THREAD

**Issue by bjsi** [supermemo/SuperMemoAssistant#46]
Currently Watcher works by subscribing to keyboard input and element changed events. The data collection works well when there are frequent input events (eg. when doing your item queue), but when reading a long article minutes can go by without keyboard input leaving big gaps in the data

**Comment by alexis-** [comment]
@bjsi Do you want to try and implement this yourself ?

**Comment by alexis-** [comment]
What are you proposing ? This seems like something that should be handled by Watcher. Wouldn't reading an article for a long time be recorded as time spent on that specific article ?

**Comment by bjsi** [comment]
I basically want to use a mouse event to know that the user hasn't gone afk. I had a look through the source code and found this part, if you think it's feasible for me to add an event somehow, I am 100% down to try and sort this myself.
![image](https://user-images.githubusercontent.com/58147075/74091726-85f0b400-4ab2-11ea-9af2-be208b131b3c.png)

**Comment by alexis-** [comment]
I think this is something that is out of the scope of SMA.
For what you want to achieve, I recommend that you hook into the system-wide input API. You will be notified on every event. SMA and plugins are already using this for keyboard hotkeys, you may have a look if you're interested.

Be very mindful when using that API, it is an important responsibility. You are dealing with something that directly impacts the user experience of the whole system.

**Comment by alexis-** [comment]
I am closing this for the time being.
