### ISSUE TITLE
Installation instructions needed for beta testers

### ISSUE THREAD

**Issue by Vesterberg** [supermemo/SuperMemoAssistant#9]
Hello, I'd like to try it out but I need some installation instructions

**Comment by alexis-** [comment]
Hi Vesterberg,

An open beta will begin in the upcoming months. If you're really eager to try it out and can't wait, reach me on the Discord channel @Alexis.Inco

**Comment by luislopes7** [comment]
hi, im trying to install oclussion editor, it says that need this, but i cant install on win 8

**Comment by alexis-** [comment]
Hi @luislopes7 

For the Occlusion Editor, please use:
- https://github.com/supermemo/SuperMemoScripts
- https://github.com/supermemo/ImageOcclusionEditor

**Comment by luislopes7** [comment]
when i trying to install SuperMemoAssistant Executable (compiled script)<https://github.com/supermemo/SuperMemoScripts/releases/download/v0.1d/SuperMemoAssistant_legacy-v0.1d.exe> windows 8 says that file cant execute


________________________________
De: Alex Incogito <notifications@github.com>
Enviado: sábado, 6 de abril de 2019 06:20
Para: supermemo/SuperMemoAssistant
Cc: luislopes7; Mention
Asunto: Re: [supermemo/SuperMemoAssistant] Installation instructions needed for beta testers (#9)


Hi @luislopes7<https://github.com/luislopes7>

For the Occlusion Editor, please use:

  *   https://github.com/supermemo/SuperMemoScripts
  *   https://github.com/supermemo/ImageOcclusionEditor

**Comment by alexis-** [comment]
SuperMemoAssistant_legacy-v0.1d.exe is the compiled version of the AutoHotKey script (.ahk) on the same repository.
There is no installation process, you should be able to run it as it is.

With the information you have given me, I am afraid I can't provide you with a direct solution. But there are at least two ways you could go about this:

1. Download the .ahk script ; Install AutoHotKey ; Run the script directly
2. Investigate, or ask on the AutoHotKey forums with details about the issue you encountered when running the .exe

**Comment by fkgruber** [comment]
I would love to beta test the incremental pdf plugin. How can I sign up for the beta testing?
thanks

**Comment by fkgruber** [comment]
> Hi Vesterberg,
> 
> An open beta will begin in the upcoming months. If you're really eager to try it out and can't wait, reach me on the Discord channel @Alexis.Inco

Hi Alexis, 
Are you talking about https://discordapp.com? What server is your channel in?

**Comment by luislopes7** [comment]
Hi, i need to know how to install the pdf plugin for supermemo
thanks

**Comment by alexis-** [comment]
> 
> Hi, i need to know how to install the pdf plugin for supermemo thanks

Hi @luislopes7 
There is no official binary for SMA and the plugins yet. If you ask around on the discord SuperMemo channel, someone might help you though. @Naess in particular has been very active in helping SMA users.



> 
> 
> Is this compatible with Supermemo 18?

Hi @klingonunderwearmodel 

SM18 compatibility is a work in progress. I will probably release an official beta binary of SMA when this is completed.

**Comment by alexis-** [comment]
https://sma.supermemo.wiki/
